berkeley: Squash: Doze bring up and fix
Fix custom doze receiver protected broadcast logspam

05-23 10:32:55.236   834 13503 E ActivityManager: Sending non-protected broadcast com.android.systemui.doze.pulse from system 1639:com.custom.ambient.display/1000 pkg com.custom.ambient.display
05-23 10:32:55.236   834 13503 E ActivityManager: java.lang.Throwable
05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19091)
05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:19603)
05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:19838)
05-23 10:32:55.236   834 13503 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:240)
05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2922)
05-23 10:32:55.236   834 13503 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:697)
05-23 10:32:55.243   834 13503 E ActivityManager: Sending non-protected broadcast com.android.systemui.doze.pulse from system 1639:com.custom.ambient.display/1000 pkg com.custom.ambient.display
05-23 10:32:55.243   834 13503 E ActivityManager: java.lang.Throwable
05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19091)
05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:19696)
05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:19838)
05-23 10:32:55.243   834 13503 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:240)
05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2922)
05-23 10:32:55.243   834 13503 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:697)

Change-Id: I132298a7acf246b8153019ce5a3f4129d9eeca4b
@ezio84

Remove Doze dialog

We don't need this, nobody does. Most users are aware of ambient display and
what is capable of.

Change-Id: I30abd53cfae1101157b92bf9b869e6469915c2f2
@Mazda--

remove redundant settings

commit a2c0c87267a5b7bc7838caa7acb2ea42f3f13a0a
@rc420head

Change package name for uniformity

With Android O we want to stick to just one package name for device specific doze.

- Set Doze package to compile
- Enable bool to hide AOSP ambient display options

Change-Id: I3279d0d3d06141f282a1135c9fb95f25e2fc994b
@Mazda--

Further Refactoring, change theme to match pixel (settings)

- Remove package from showing up in settings

- Changed package name so we can do our own thing and not have it
get in the way of the Doze package currently used by Nick and others

- Set OneplusDoze to compile

Change-Id: Ieebf13f88c02d5036a09b5ef83ca1b53bd6999ac
@Mazda--

Clean up doze

* remove always enabled option
* use stock fade in delay

Change-Id: Ieebf13f88c02d5036a09b5ef83ca1b53bd6771ac
@Altaf-Mahdi

Doze improvements

* restructure the app
* add a tilt sensor from hammerhead-caf with an option to enable/disable
* add a one time dialog on first start to help users understand how the app works
* remove proximity wake up option and add an option to enable the sensors as soon as the screen turns off
* adjust and add new doze configs

Change-Id: Ia9d9a807d6c4f1a80a2ba8780e7486560f9a1d87
@Altaf-Mahdi

Refactoring for the OnePlus 3/T

Change-Id: I73b610bc71bf07b2fdedb1d5c5931e90f9e9de0f
@deVorteX

Remove summary for Doze

* Doesn't look good

Change-Id: Id7716387688080b5ce0a99a4d968e210d8eed6f8
@TheStrix

ScreenType util from cmsdk

Change-Id: I73b610bc71bf07b2fdedb1d5c5931e90f1e6de0f
@mikeNG

Properly fix future timestamp error

Previously attempted fix at review.cyanogenmod.org/#/c/104083/
The timestamp isn't in the future, that would be impossible.
The real issue is the timestamp from the SensorEvent is a true
timestamp, the System.nanoTime is nanoseconds since boot.
So the previous patch would always return false and never pulse.
I've simply changed it so that the wakeup call gets sent the current
System.nanoTime in milliseconds since boot so it does not think the
event came from the future since the wakeUp method expects
uptimeMillis, not true world time.

Change-Id: I78f5e9d61107caf9c3bf6c10fa7c5bb400082294
@deVorteX

Prevent a pm wakeup with a timestamp in the future

Prevents:

java.lang.IllegalArgumentException: event time must not be in the future
at android.os.Parcel.readException(Parcel.java:1550)
        at android.os.Parcel.readException(Parcel.java:1499)
        at android.os.IPowerManager$Stub$Proxy.wakeUp(IPowerManager.java:550)
        at android.os.PowerManager.wakeUp(PowerManager.java:666)
        at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.shouldPulse(SamsungDozeService.java:95)
        at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.onSensorChanged(SamsungDozeService.java:75)
        at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:405)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:122)
        at android.app.ActivityThread.main(ActivityThread.java:5289)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

Change-Id: I8ed248271d67216e531b124bf27101fa538f1195

Signed-off-by: Brandon McAnsh <brandon.mcansh@gmail.com>
@bmc08gt

Restore proximity wake preference on boot

Change-Id: I614772d6ff1005968a7f8f1ed0349e3878ddadf1
@nardholio

Add proximity wake

Change-Id: Ib02f4611e7b8bc09d540ca5c49aab68ef27f188b
@nardholio

Add back button to action bar

Change-Id: Ia56183c8c2d5a6bc25c84f1d1b9823b84bc936c9
@luca020400

Fix defaults

Change all defaults to false

Change-Id: I2df507b2fc823d3fb07bce89d44067db565a5ab8
@nardholio

Consolidate doze settings

* Allow user to disable ambient display from gesture panel
* Disable/enable doze settings based on ambient display state

Change-Id: I0ff7686ccc04037b3ada9a8355384ba6746cf30c
@crpalmer

Set gesture to disabled by default

Change-Id: I0bf3f6a3a4c01bab7ff7522e916e2149f9cfe8d5
@arco

Fix typo

Change-Id: Id7716387688080b5ce0a99a4d968e210d8eed6f9
@nardholio